### ISSUE TITLE
Cagliari - 27th June 2015

### ISSUE THREAD

**Issue by kildem** [nodeschool/italy#10]
We're organizing an upcoming nodeschool event in Cagliari, Sardinia:

https://nodeschool-italy-cagliari.eventbrite.it

Mentors:
@kildem
@mpili
@Pietrangelo
@mmorini71
@simonekalb

**Comment by simoneb** [comment]
I think it should not be too difficult to find mentors in the area, their task is mostly (depending on the workshop, but most are very simple) to assist people if they're stuck, so a little experience with node and having done the workshop before is, I believe, all that is needed.

It might not be feasible to get mentors to come from _the continent_, the travel expenses being the major trouble I guess, but in case someone is in the area for their holidays... :)

**Comment by kildem** [comment]
Hi @simoneb could you be interested to be a Mentor? Or do you know somebody that can do it?

**Comment by simoneb** [comment]
I would like to but it would be too expensive to come only for the event, nevertheless I've contacted a couple of people who might be interested, I pointed them here so they'll show up if they're interested.

**Comment by kildem** [comment]
I think it could be a great opportunity to visit Sardinia (https://www.facebook.com/VisitSardinia) there are many beautiful place ;) my Skype contact is kylden, you can contact me via Skype

**Comment by simoneb** [comment]
@kildem I've been to Sardinia already, it certainly is a beautiful place, for the sea especially.

**Comment by kildem** [comment]
I've created a web page for promoting this event: http://www.fierp.help/njschool.

**Comment by kildem** [comment]
Can somebody help me to organise this event? If he cannot come in Sardinia, It would be helpful to receive some hint on how to organize the event.

**Comment by simoneb** [comment]
@mcollina organized the last event in Bologna, maybe he has some advice for you? 

Generally though, you should find a venue to host the event and a few people as mentors. They don't need to be nodejs experts, it's important that they are somewhat familiar with it and have tried the workshops before so they can help other people when they're stuck. As for the venue, the more central it is (so Cagliari is probably better than 20km away) the more people are likely to be willing to come.

Once it's all set up and you have advertised the event I believe people will show up.

**Comment by kildem** [comment]
Where I live I don't find anyone that have tried the workshops before. That's my main problem :(

**Comment by kildem** [comment]
Thank you very much @simoneb you are the only one that answer my questions in this issue :+1:

**Comment by kildem** [comment]
Should I open another chapter Cagliari/Italy?

**Comment by mcollina** [comment]
What you should do is:
1. select a venue
2. pick a date
3. make noise to get attendees

I am trying to keep this cohesive as an Italian community.

**Comment by kildem** [comment]
I think in order to keep this cohesive as Italian community at least one member or collaborator of this chapter should spend time to collaborate with Cagliari event. I can understand It requires effort and time that may be nobody of this group have.

**Comment by simoneb** [comment]
@kildem what do you need help with?

**Comment by kildem** [comment]
Do you have time to have a video conversation with me via Skype?

**Comment by simoneb** [comment]
@kildem ping me on skype {firstname}_{lastname} (you can find this info on my github profile page)

**Comment by kildem** [comment]
:+1:

**Comment by kildem** [comment]
One thing is not clear to me: If I don't open e new chapter Cagliari/Italy, (after I 1) select a venue 2) pick a date), how can I add the event in http://nodeschool.io/events.html page?

**Comment by StefanoF** [comment]
I live in Cagliari and i like to partecipate at this event.
I can contribute with your organization for this step: "make noise to get attendees". I already share the idea of this event with others people and they think it's a good idea! So good luck!

**Comment by simoneb** [comment]
That's a great start! As I suggested to @kildem the next step is to pick a
date and a venue so that people can begin subscribing.

I live in Cagliari and i like to partecipate at this event.
I can contribute with your organization for this step: "make noise to get
attendees". I already share the idea of this event with others people and
they think it's a good idea! So good luck!

**Comment by kildem** [comment]
Thank you very much @StefanoF!
I'm planning to take this event not before June 2015 and within September 2015.

**Comment by kildem** [comment]
added mentors at the top of this issue

**Comment by kildem** [comment]
This is the result of this [survey](goo.gl/fwoJgh)  :

![survey250615](https://cloud.githubusercontent.com/assets/1815732/8349377/79cfc29e-1b1c-11e5-8507-2bc69580464c.png)

23 people submit the survey. 
Hopefully more participant will submit the survey.

**Comment by piccoloaiutante** [comment]
Is there any other mentor that would like to join us? We are currently five people :-)

**Comment by kildem** [comment]
Thank you very much for all people that this morning participated to the first NodeSchool event in Cagliari!
http://youtu.be/fP1gDDF9Fww

https://www.youtube.com/watch?v=2jNJY6tU8BE

**Comment by simoneb** [comment]
Nice clip! Thanks for posting

**Comment by kildem** [comment]
New event on 19th September 2015 https://nodeschool-cagliari.eventbrite.it
https://github.com/nodeschool/italy/issues/21
