### ISSUE TITLE
Update of the "Italy page

### ISSUE THREAD

**Issue by marcopiraccini** [nodeschool/italy#11]
http://nodeschool.io/italy/ still refers the the "first" event. We probably should add a link to the "next" event discussion / eventbrite page.

**Comment by mcollina** [comment]
Yes, you can push to the gh-pages branch and update it!
Il giorno mer 18 mar 2015 alle 15:19 Marco notifications@github.com ha
scritto:

**Comment by mcollina** [comment]
Also, you should register the event in Rome!
Il giorno mer 18 mar 2015 alle 17:17 Matteo Collina <
matteo.collina@gmail.com> ha scritto:

**Comment by marcopiraccini** [comment]
Ah, ok, I didn't see the branch :) (and ok, I forgot that gh-pages is the naming convention for the project pages :) )

**Comment by marcopiraccini** [comment]
Done.
