### ISSUE TITLE
Modena - 6th May 2015

### ISSUE THREAD

**Issue by simoneb** [nodeschool/italy#12]
Hi everyone! We're organizing an upcoming nodeschool event in Modena, Emilia Romagna, home to great food and wine traditions (pretty much like any other part of Italy!).

It will be on the **6th of May at [LOFT350](http://loft350.it/), Modena**. 

Sign up as an attendant or get a mentor ticket (only if you would like to help as a mentor). Tickets are sold out but you can sign up for the waiting list, it's likely that some seats will become available at some point.

http://nodeschool-modena-may2015.eventbrite.com/

**Please make sure** that you have filled-in the [workshop preference and dinner survey](http://goo.gl/forms/MNRiY5FJc3), it's important for us to decide which workshops to do and to organize the dinner (10-15 €, all included).

Any doubts or questions? Just comment on this issue!

**Comment by marcopiraccini** [comment]
Perfect. Count on me as a mentor.

**Comment by gpad** [comment]
When do you want organize it?

**Comment by simoneb** [comment]
Not sure yet, I'm checking the availability of venues, no earlier than mid-April though.

**Comment by double-m** [comment]
cool!

**Comment by ubaldop** [comment]
Hi there, will be held during the weekend?

**Comment by simoneb** [comment]
@P3trur0 no actual plans yet, most likely not though

**Comment by simoneb** [comment]
We have an initial idea for a date and a location: **6th of May at [Loft350](http://loft350.it/), Modena**.

Shortly we'll have an EventBrite page and a survey for the selection of workshops.

**Comment by simoneb** [comment]
@marcopiraccini can you please get in touch with me? I'd like to create the event on eventbrite.

**Comment by marcopiraccini** [comment]
Sure. Do you have a Skype account? Mine is marcopirac

**Comment by simoneb** [comment]
All set, we've got an event page on EventBrite and a survey to collect votes on the workshops to do and for the dinner.

Please sign up as an attendant or get a mentor ticket only if you would like to help as a mentor.
- NodeSchool Italy - 1st event in Modena - http://nodeschool-modena-may2015.eventbrite.com/
- Workshop and dinner survey - http://goo.gl/forms/MNRiY5FJc3

**Comment by marcopiraccini** [comment]
@piccoloaiutante: Can you tweet about that? (I don't have the @nodeschool_it password...by the way, send it to me :)).

**Comment by simoneb** [comment]
Good idea, we still have seats available so let's make some noise.

**Comment by piccoloaiutante** [comment]
Good morning, i've just retweeted saturday tweet, do you want to send another one tomorrow morning?

**Comment by mcollina** [comment]
I think we can set up a Buffer account.

**Comment by simoneb** [comment]
We're sold out! The venue can arrange a buffet dinner so I'll shortly send out a reminder to fill-in the survey to see how many people will stay for dinner (I advise to stay, the place is cool!). I'll set up a waiting list as well.

@mcollina @marcopiraccini are there any leftover stickers from the previous meetup that we can distribute? Or, how do I print more?

**Comment by simoneb** [comment]
Also, we need a couple of mentors, I asked a few people already but I'm not sure they'll be in, so if anyone would like to help out as a mentor please get a mentor ticket on the eventbrite page.

I'll try to publish the list of preferred workshops soon.

**Comment by marcopiraccini** [comment]
@piccoloaiutante  is the sticker guy :)

**Comment by piccoloaiutante** [comment]
I could try to come but i'm not sure. If you want I can send them to you @simoneb so that we're sure that you have it.

**Comment by simoneb** [comment]
@piccoloaiutante I'm often in Bologna, are you in the area?

**Comment by piccoloaiutante** [comment]
@simoneb not really, i'm based in Brescia :-)

**Comment by simoneb** [comment]
@piccoloaiutante I see, depending on what is more cost-effective either send them to me or I can print them anew

**Comment by marcopiraccini** [comment]
But how many stickers we have? Maybe it's a good idea to print a new batch for the next events (Bologna, Modena, Milano).

**Comment by piccoloaiutante** [comment]
I think i have more than 100 stickers so i would suggest to use them and then reprint it. But again as you prefer..

**Comment by simoneb** [comment]
Sure, why not. Where did you print them?

**Comment by piccoloaiutante** [comment]
Pixartprinting

**Comment by piccoloaiutante** [comment]
200 stickers for 100 euro

**Comment by simoneb** [comment]
100 stickers is more than we need btw, how much did you pay for them? I
quick quote I got is more than 100 €, so I guess sending them by post is
going to be much cheaper.

**Comment by piccoloaiutante** [comment]
yeah that's why i thought to send them to you ;-) send me your address at michelecapra83 at gmail dot com

**Comment by diegobent** [comment]
Hello everyone! @simoneb I can try to help you as mentor for learnyounode..

**Comment by simoneb** [comment]
@diegobent sure feel free to come, grab a mentor ticket and let me know if you're staying for dinner.

**Comment by simoneb** [comment]
These are the results of the survey on the workshops:

| workshop | votes |
| :-- | --: |
| javascripting | 7 |
| learnyounode | 6 |
| async you | 6 |
| expressworks | 5 |
| promise-it-wont-hurt | 3 |
| test anything | 2 |
| how to npm | 2 |
| ui frameworks | 1 |

I propose we do the first three: **javascripting**, **learnyounode** and **async you**. There should be 10 people joining for dinner so I'll ask LOFT to prepare some food.

See you on Wednesday at around 7 PM!

**Comment by thehowl** [comment]
Hey,

since I'm under 18, is a parent required in order to subscribe to FENALC?

**Comment by simoneb** [comment]
@TheHowl if you got a ticket feel free to come, that's not going to be a problem for sure

**Comment by thehowl** [comment]
I wouldn't ask that question if I hadn't got a ticket :P

On 6 May 2015 00:46:24 CEST, Simone Busoli notifications@github.com wrote:

> @TheHowl if you got a ticket feel free to come, that's not going to be
> a problem for sure
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nodeschool/italy/issues/12#issuecomment-99253142

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
