### ISSUE TITLE
Reggio Emilia - 1st July 2015

### ISSUE THREAD

**Issue by simoneb** [nodeschool/italy#13]
Hello!

We're organizing a new meetup, **the first in Reggio Emilia**, on 1st July.

Tickets are sold out but you can add yourself to the waiting list **[here](http://nodeschool-reggio-emilia.eventbrite.com)**.

We need **mentors** now, who's joining us?

**Comment by ilbonzo** [comment]
:+1:

**Comment by marcopiraccini** [comment]
Do you already know the date?

**Comment by simoneb** [comment]
Not yet, I'll update the issue as soon as I have more info. Most likely
beginning of July though.

**Comment by thehowl** [comment]
If it's in the first ~5 days of July, I might be able to come!

**Comment by simoneb** [comment]
We'll be holding the event on 1st July at ImpactHub Reggio Emilia, details and subscriptions [here](http://nodeschool-reggio-emilia.eventbrite.com).

**Comment by lambrojos** [comment]
I was thinking about coming around and help out with mentoring, but I noticed it's on wednesday evening, this makes impossibile for me to be there..

May I ask why this date was chosen?
Today I was chatting with Luca Vettorello from ImpactHub and he and others from the coworking are worried that very few people will come on a working day evening..

**Comment by simoneb** [comment]
@lambrojos to my knowledge all other meetings in the area except for the event in Milan on the international NodeSchool day were held during weekdays.

As far as I know the space is limited (approx 20 ppl) and 14 tickets were sold already, so I don't see the concern.

You're very welcome to help organize next time though, this ticket was opened with TBD dates two weeks ago now.

**Comment by lambrojos** [comment]
Of course I did not want to make you change date, I knew subscriptions where open for a while.. Actually I am pretty new to this kind of things, I assumed saturdays where almost the default day for workshops and the like ;)

**Comment by simoneb** [comment]
@lambrojos really depends. For a whole day conference weekends are common. For shorter meetings like these weekday evenings are good too, as most people come straight from work. There'll be more meetings though, we can certainly try a different day next time.

**Comment by simoneb** [comment]
We are now sold out. Who's joining as a mentor? Don't be shy!

**Comment by simoneb** [comment]
Mentors needed. We're going to be more than we thought, probably more than 30 people. Who's helping out?

**Comment by marcopiraccini** [comment]
I will probably be there, but I have to check the trains :)

**Comment by simoneb** [comment]
@marcopiraccini I might be coming by train too, the place is pretty close to the station, 1km approx

**Comment by gpad** [comment]
Is time the same?
It's difficult arrive in Reggio at 18:00 :-(

2015-06-22 9:25 GMT+02:00 Simone Busoli notifications@github.com:

**Comment by simoneb** [comment]
@gpad your presence would be much appreciated :) Don't worry about the time, we won't be doing much until at least 18:30 / 19:00 I guess

**Comment by double-m** [comment]
Hi all!
Count on me as mentor

**Comment by gpad** [comment]
@simoneb Count on me!!!

**Comment by simoneb** [comment]
:+1:

**Comment by simoneb** [comment]
Based on the preference expressed by participants in the survey we'll be doing learnyounode for sure, then probably ExpressWorks, but I would leave the choice to do what everyone prefers.

We'll have a JetBrains license to give as a prize and I prepared a [small script](https://github.com/simoneb/nodeschool-prizes) to pick a winner.

We have the option to eat at a nearby restaurant after the event, we'll set everything up during the evening.

See you on Wednesday!

**Comment by gpad** [comment]
:+1:
