### ISSUE TITLE
Bologna

### ISSUE THREAD

**Issue by marcopiraccini** [nodeschool/italy#14]
I open new issue for the Bologna events.

Informally, we can use WCAP again for the third meeting around mid-July (for instance, the 23th of July).

My idea was to organize the event in a slight different way: assuming that we will run again "learyounode" for the newbies, my idea was to focus on only one other (advanced) workshop, with a small presentation at the beginning to introduce the topic.  

What do you think?

**Comment by ilbonzo** [comment]
I like this idea, I did learnyounode and would like to continue the path with the right support

**Comment by gpad** [comment]
:+1:

**Comment by marcopiraccini** [comment]
OK guys, next event will be the 31th of July! 
Sorry for the short notice :). We will discuss here what will be the contents

**Comment by mcollina** [comment]
I am so sorry but I won't be able to attend.

**Comment by simoneb** [comment]
I'm in but it's a short notice and during holiday time, I'm not very confident that there will be much attendance. I would set up the EventBrite page asap to see how many people would subscribe, let me know if you need any help.

**Comment by marcopiraccini** [comment]
We'll see...I'm going to prepare the Eventbrite event later.

**Comment by simoneb** [comment]
We've got 2 JetBrains licenses to give away for this event.

**Comment by marcopiraccini** [comment]
Ok, great!

**Comment by simoneb** [comment]
@marcopiraccini no event yet, only 2 weeks in advance during summer? you must be very positive about the attendance :smile:

**Comment by marcopiraccini** [comment]
I'm going to publish the event today...as usual, WCAP guys asked me to wait until they publish the event on Facebook. 
And yes, I'm very positive! :D

**Comment by simoneb** [comment]
Great! I was thinking, why don't we come up with our own Italian-themed workshop? After playing with the framework a bit I realized it's not that hard to write one, but I haven't had many ideas about a worthwhile topic. Any ideas?

**Comment by marcopiraccini** [comment]
It's a good idea, I'm going to open a new issue on that!

**Comment by gpad** [comment]
@marcopiraccini count me as mentor. My company @coders51 are searching some node.js developers so if possible spread the word ... :-)

**Comment by marcopiraccini** [comment]
Here the eventbrite link! https://www.eventbrite.com/e/nodeschool-bologna-summer-edition-tickets-17742796181

**Comment by simoneb** [comment]
:+1:

**Comment by valep27** [comment]
I'm gonna ask the most important question, does WCAP have air conditioning? I'm too young to die.

**Comment by marcopiraccini** [comment]
Sure!

**Comment by keul** [comment]
Not this time... I won't be able to attend

**Comment by marcopiraccini** [comment]
See the logo that the WCAP guys prepared...it's awesome :) https://www.facebook.com/events/454068124795076/

**Comment by simoneb** [comment]
I also liked the [one](http://36.media.tumblr.com/c9c6a2b6b2657eecaf1b78784920dc9a/tumblr_inline_nnxr8wtH471r08vln_500.png) they did when we met in modena!

**Comment by Markesi** [comment]
Hi to all,
I would like to contribute to the summer event in Bologna.
Who is the coordinator of the translations? 
What kind of attendance is expected? 
What kind of mentoring is needed?

for reference, look at my profile on Linkedin: Michelangelo Marchesi

**Comment by marcopiraccini** [comment]
Hi Michelangelo, 

Not sure what "coordinator of the translations" is, but I'm organising the event.
The attendance is normally developers, some new with node, other more experienced. We have yet to figure out which workshop we will execute.
The mentoring is simply help people when blocked in executing the workshop and answer their questions.

**Comment by marcopiraccini** [comment]
OK guys, 
My proposal is to execute:
- For the NodeJS/JS newsbies: The brand new "Scope Chains & Closures" + Learnyounde 
- Middle level: async you
- Advanced: learnyoureact 

If I have time, I will prepare a longer (max 20 minutes)  introduction on NodeJS architecture (a lot of people asked for it last times).

**Comment by gpad** [comment]
Hi @marcopiraccini Do you know how the people are distributed? 

:+1: for NodeJS architecture

**Comment by marcopiraccini** [comment]
I've just sent the usual form, however I expect a majority of basic / middle Nodejs-JS skill

**Comment by marcopiraccini** [comment]
Great job guys! The event was a success, although the date!

**Comment by marcopiraccini** [comment]
It's time to think about the next event! I will probably be very busy in September, so it's probably better to target on October (after nodejsconf). 
My idea is to focus on ES6. Up to date, There are 4 workshop about that:
- count-to-6
- esnext-generation
- learn-generators
- tower-of-babel

... + a (short) introduction about the history of JavaScript language and the standard (any volunteer? :))

What do you think about it?

**Comment by mcollina** [comment]
I would like to target September with an event the night before http://2015.fromthefront.it/, so the 16th of September.

A lot of people might be in town, and I think it can be a great success. What do you think?

cc @cedmax

**Comment by cedmax** [comment]
Hi guys, that's fine for us, just please avoid branding it, even unwillingly, as a From the Front "side" event: we'd be glad to help sharing the news (maybe also in the newsletter, not just RT, but I'll have to check with the rest of the staff), but it needs to be clear that it's managed by different entities and it's not a fringe of our conference managed by ys. 

I hope it does make sense for you :)

**Comment by mcollina** [comment]
@cedmax it was the exact reason why I brought you in the discussion. Let us know if it is something it can be of interest for the ftf team, and if you would like to advertise it in the newsletter. If you are planning something for that night, we will not do a 'conflicting' event.

**Comment by cedmax** [comment]
We don't have anything official for that night apart from the speakers' dinner, but that is not an issue at all as it doesn't involve neither attendees nor volunteers, but just the core staff and the speakers.

It would actually be the best day (the day after we have the official party), if you are organising drop me a line via email and I'll try to sneak it in the newsletter ;)

**Comment by marcopiraccini** [comment]
OK, I can ask if the 16th of September is good for WCAP

**Comment by marcopiraccini** [comment]
Asked. For them the 17th is better since the 16th the WCAP is already booked for other activities. It would fit the same?

**Comment by cedmax** [comment]
@marcopiraccini as I mentioned on the 17th we'll have the conference party for the attendees, we won't be able to endorse to them your event if that's on that night, sorry about that
