### ISSUE TITLE
JetBrains sponsorship

### ISSUE THREAD

**Issue by simoneb** [nodeschool/italy#15]
I recently asked JetBrains if they were willing to support the NodeSchool Italian community with free licenses for their products to give away during our meetings. I'm myself a WebStorm user, hence why I asked them rather than some other company.

They accepted and we have currently 3 licenses that we can start giving to attendees and we should be getting some every month. In theory, 2 of these 3 should be going to organizers, but I'm honestly more inclined to give them to attendees given that we have a few upcoming meetings, and eventually keep 2 for organizers in the future (I do not need one myself).

If everyone agrees I intend to give two or one for the Cagliari meeting, one or two for Reggio Emilia and hopefully 2 or 3 for the late July Bologna meeting, assuming that we get another batch of licenses next month.

How does it sound?

**Comment by kildem** [comment]
Thank you very much @simoneb? It sounds good.
WebStorm is awesome, I've used a free trial but my WebStorm evaluation has expired.
One question: How is it possible to give one license to one out of 30 attendee?

**Comment by simoneb** [comment]
As there are no further ideas I'm planning to give 2 licenses to #10 and keep one for #13 which we'll give to attendees.

**Comment by marcopiraccini** [comment]
For me it's OK.

**Comment by mcollina** [comment]
OK for me
Il giorno ven 12 giu 2015 alle 21:51 Marco notifications@github.com ha
scritto:

**Comment by kildem** [comment]
:+1: Thanks
