### ISSUE TITLE
Brescia

### ISSUE THREAD

**Issue by piccoloaiutante** [nodeschool/italy#16]
I've been recently asked if there is anyone that want to organise a node school event in Brescia.I'n up for it :-) Is there anyone else?

**Comment by simoneb** [comment]
Sure, if you need any help I'm in as a mentor, and to help with setting it up too.

**Comment by piccoloaiutante** [comment]
Good let see if @MasterTheBest would also like to join us..

**Comment by RedsAnDev** [comment]
Hola!
I'm a very newbie: so what can I do for you?

**Comment by gpad** [comment]
Hi Michele,
I can help you if you want it :-)

2015-06-15 14:25 GMT+02:00 Andrea Rossi notifications@github.com:
