### ISSUE TITLE
Codemotion Milan 2015

### ISSUE THREAD

**Issue by mcollina** [nodeschool/italy#18]
How about we propose a workshop at http://milan2015.codemotionworld.com/? In Rome it was a blast.

**Comment by simoneb** [comment]
@mcollina definitely! Great idea

**Comment by marcopiraccini** [comment]
Sure, count on me!

**Comment by mcollina** [comment]
Who wants to lead this one?

cc @lambrojos @teone @teomurgi @piccoloaiutante

**Comment by piccoloaiutante** [comment]
I could lead this one.. since i have the form ready form the Rome one :)

**Comment by teone** [comment]
I can come to help, count on me! And I'm pretty sure that @lambrojos will help too

**Comment by piccoloaiutante** [comment]
I've just imported the previous one from Codemotion Rome, then i just need to add all mentors email..

**Comment by simoneb** [comment]
count me in too

**Comment by mcollina** [comment]
count me in too :)

**Comment by lambrojos** [comment]
I'm in !

**Comment by lambrojos** [comment]
I was also talking  with @pietro909 and his webgl friends.. they where interested in running a webgl table, I think there are a couple of workshoppers about this kind of stuff. 
It's not strictly node, but I think this could draw more interest to the event.. what do you think?

**Comment by marcopiraccini** [comment]
@lambrojos / @pietro909 about webgl, see also this brand new topic: https://github.com/nodeschool/italy/issues/19

**Comment by pietro909** [comment]
thank you @lambrojos for the proposal and @marcopiraccini for pointing it out: we are keen to help with spreading WebGL technology through presentations, use cases, and workshops (hands-on).
Let us know whether you want us to collaborate with you.

**Comment by piccoloaiutante** [comment]
guys, quick reminder to answer to codemotion email to join as cospeaker at the workshop

**Comment by piccoloaiutante** [comment]
proposal seems not accepted..but i haven't received any info yet..

btw in the meantime we're finalising a node school event in milan here #22

**Comment by piccoloaiutante** [comment]
ok so we haven't been accepted so i'll close this issue

**Comment by simoneb** [comment]
Seriously? :(

**Comment by piccoloaiutante** [comment]
Yes, @mcollina knows more about it..
