### ISSUE TITLE
Multimedia NodeSchool 

### ISSUE THREAD

**Issue by marcopiraccini** [nodeschool/italy#19]
Guys, 

In October in Bologna will take place the roBOt Festival  (http://www.robotfestival.it/2015/index.html).
They are asking me if it's possible to organize during the festival a NodeSchool event on "multimedia" NodeJS. Indeed there are some workshops on that:
- Intro to WebGL
- WebGL Workshop
- Shader School
- Web Audio School

Anyone is interested in mentoring/helping with that?

**Comment by piccoloaiutante** [comment]
Unfortunately not this time, because is too close to nodejsconf.it and i bet i'll be busy :-)

**Comment by marcopiraccini** [comment]
Yes, indeed for the same reason I will not be in Bologna the 10th. Also the 9th it's my birthday, so this will probably happen the 7th or the 8th.

**Comment by pietro909** [comment]
hi @marcopiraccini we had a 4 days workshop in Milan last June (please have a look at [3dweb](http://www.3dweb.cc)).
The workshop type I prefer is "hands on": coding live making simple steps to the final result.
We also made a brief introduction about WebGL that could go a little bit deeper to fit a regular talk [demystingying the 3d web](http://www.slideshare.net/pietrograndi3d/demistifying-the-3d-web).
What do you think about it?

thank you, have a nice day!
pietro

**Comment by marcopiraccini** [comment]
4 days is too much :).
The NodeSchool formula it's always "hands on" (take a look at the workshops here: http://nodeschool.io/)  but an introduction would be good.

Some points on this event:
- The roBOt festival it's quite big. The person who is asking for the NodeSchool "multimedia" event is the head of the communications for the festival, so we will have a lot of visibility.
- It would be good to "produce" something with WebGL / Web audio during the event. Maybe after the "school" we can have a (small) hackaton to produce something "visible/audible". 
- As any other NodeSchool events, this will be free.
- Logistic will not be a problem, we have the availability of WCAP

**Comment by pietro909** [comment]
Thank you Marco,
of course the final result of the workshop must be a nice to see / good to show to teammates product :-)
Free is ok, even our event was free and the hackaton is always welcome as well if we have the time.
Would you like me to prepare a brief roadmap proposal for such a workshop?

**Comment by lambrojos** [comment]
@marcopiraccini will it be a multimedia only event? Or there will also be space for the good old non-multimedia workshoppers?

**Comment by marcopiraccini** [comment]
I'm back on the topic :)

@pietro909: Not sure what a "roadmap proposal " is, however: first, we must fix a date (7 or 8 October) and then decide the event details, but realistically the structure will be the same as any other NodeSchool events:
- Quick presentation of the technologies (WebGL, Web Audio). If you already have a presentation, we can reuse it. 
- Execution of the workshops (usually grouped in tables). I didn't execute these workshops yet, but usually they are quite "basic". 

In this event we can add a quick hackaton  to produce something "visible". If good, we could make it public and give visibility through the roBOt festival channels. Usually our events last about 3 hours, but since we have the WCAP availability, we can make it longer.

@lambrojos: As long we have space, why not?

**Comment by pietro909** [comment]
Ok @marcopiraccini, the _roadmap_ is just a raw document defining goals, steps and timing of the event. The quick presentation is about 20 minutes (the very quick one) while a workshop, although quick, couldn't take less than 2 hours (with people which know js and are confident in writing a small web page).

**Comment by marcopiraccini** [comment]
In the meanwhile, the date has been fixed for the 8th of October  (I will publish the Eventbrite event soon). 

@pietro909: we must have time also to run the NodeSchool workshoppers, some of them (we have to decide which ones yet), e,g:
- https://github.com/stackgl/webgl-workshop
- https://github.com/alexmackey/IntroToWebGLWithThreeJS
- https://github.com/mmckegg/web-audio-school

If you want, we can discuss the organisation directly (on skype or hangout, choose one :)).

**Comment by pietro909** [comment]
cool! 
Please let me the time to read those workshop in order to have a clear situation of timing and goals.
We also as Khronos Milan prepared some tutorials which build a whole four days workshop, if you are interested.

Anyhow, a direct call will be the best. 
How do we manage it? I'm available either on skype or hangout.

**Comment by marcopiraccini** [comment]
OK Guys, all confirmed for the 8th of October!
The title of the event will be "NodeSchool: Interactive 3D  with WebGL and ThreeJS" 
Eventbrite event will follow soon.

**Comment by marcopiraccini** [comment]
Event open! Note that we are in "Palazzo D'Accursio" (piazza Maggiore) instead of WCAP. http://www.eventbrite.com/e/nodeschool-interactive-3d-con-webgl-e-threejs-tickets-18538741876

**Comment by marcopiraccini** [comment]
Ok, event full :). Waitlist open!

**Comment by diegobent** [comment]
Sorry guys but I can't help you! I don't know this arguments and on 8th Oct
I'll be also at work!
See you at nodejs conference!

Il giorno sab 26 set 2015 09:44 Marco notifications@github.com ha scritto:

**Comment by marcopiraccini** [comment]
http://www.robotfestival.it/2015/events/edu2fworkshop/119/nodeschool.html

**Comment by marcopiraccini** [comment]
The event was a HUGE success thanks to @pietro909 !
