### ISSUE TITLE
Modena - 17th September

### ISSUE THREAD

**Issue by simoneb** [nodeschool/italy#20]
Hello, I'm planning the next event in Modena. It will be on 17th September at LOFT350.

http://nodeschool-modena.eventbrite.com

Who's in (for mentoring, too)?

**Comment by marcopiraccini** [comment]
The 2nd week of September I will be at http://nodeconfeu.com/ (with @piccoloaiutante and @mcollina).

**Comment by simoneb** [comment]
Good point. For those of us not as lucky there will be the Modena event then :smile:

**Comment by double-m** [comment]
Hi, count on me as mentor.
:+1: for LOFT365

**Comment by simoneb** [comment]
The event is live at http://nodeschool-modena.eventbrite.com

Thursday 17th September at LOFT350, Modena

**Comment by llagit** [comment]
Hi all, there is any schedule/plan for this evening? Speech sessions? Thank you

**Comment by simoneb** [comment]
Hi Luca,

If you've never attended a NodeSchool event, we don't have speakers and sessions, instead we do interactive workshops more like a coding dojo, exercises that teach you something about Node.js.

There's a long list of available workshops on the NodeSchool website, we usually propose a few of the based on the audience of the event but choosing a different one is always possible.

For tonight our list is javascripting (for people who don't know JavaScript), learnyounode, async-you and expressworks.

Simone
