### ISSUE TITLE
Milan October

### ISSUE THREAD

**Issue by piccoloaiutante** [nodeschool/italy#22]
Ehi, who is up for a node school in Milan next month around 19-24th of October?

**Comment by kamakay** [comment]
I am really really interested.Roberto

—
Inviato da Mailbox

**Comment by lambrojos** [comment]
I'm in!

**Comment by kamakay** [comment]
Hi all,

any news about the event? Do you have an idea about location or feasibility?

Roberto

2015-09-15 9:52 GMT+02:00 lambrojos notifications@github.com:

**Comment by piccoloaiutante** [comment]
Yes the work is in progress and we're still deciding date and location.

I should have new news by the start of the next week :-)

**Comment by kamakay** [comment]
Hi Michele,

I don't know if this could be usefull, here in 7Pixel we can arrange events
and other stuff (XPugs and code retreat).

If you have location issues you could also consider our venue.

Roberto

2015-09-23 14:59 GMT+02:00 Michele Capra notifications@github.com:

**Comment by lambrojos** [comment]
Also Mikamai's venini42 space is available free of charge
It's really large and near Milan central station

take a look http://venini42.it

**Comment by kamakay** [comment]
I have seen the venue, cool! What about the date?
R.
Il 24/Set/2015 10:35, "lambrojos" notifications@github.com ha scritto:

**Comment by piccoloaiutante** [comment]
I was thinking about the end of October during the week. Something like nodeschool + pizza. How do you see it?

**Comment by piccoloaiutante** [comment]
Btw I hope to see you all at nodejsconfit :-)

**Comment by kamakay** [comment]
Personally I would prefer the week starting from 26 october :)
Il 25/Set/2015 20:40, "Michele Capra" notifications@github.com ha scritto:

**Comment by lambrojos** [comment]
Nodeschool + pizza sounds like a deal to me!
I have no particular preferences about the week
@nkint will you join us?

**Comment by nkint** [comment]
I'm in! 
No preferences for the week..

**Comment by teone** [comment]
I'll be in!

No preference for the date. 
As location _Mikamai's venini42_ suggested by @lambrojos is cool and near to M1 stop Pasteur, can be easily reached with public transportation.

**Comment by piccoloaiutante** [comment]
So how about Tuesday 27th at Mikamai's office?

**Comment by teone** [comment]
@piccoloaiutante what about 28th?

On 27th there is this event about Docker from Milano Tech Scene: http://milanotechscene.it/#calendar 
normally we try to don't run events on the same night to allow people to follow eveything :)

**Comment by piccoloaiutante** [comment]
yeah lets do it on 28th!

**Comment by teone** [comment]
Ok, if it's ok to everyone tomorrow we'll lock the date at mikamai

**Comment by teone** [comment]
Mikamai confirmed the spaced for 28th October from 19:00

**Comment by piccoloaiutante** [comment]
Good,
so how many mentors are we going to have? I see that there are 5 people in this discussion..

**Comment by piccoloaiutante** [comment]
@teomurgi are you going to join us?

**Comment by kamakay** [comment]
Presente con un altro collega.
Roberto
Il 06/Ott/2015 11:44, "Michele Capra" notifications@github.com ha scritto:

**Comment by piccoloaiutante** [comment]
Event is ready! Spread the verb ;-)

https://www.eventbrite.it/e/biglietti-nodeschool-milano-18974151197

**Comment by teone** [comment]
For resume as mentor:
- me
- @lambrojos 
- @nkint 
- @piccoloaiutante 
- @kamakay 
- @kamakay workmates
- @teomurgi 

Anybody else?

**Comment by piccoloaiutante** [comment]
@simoneb ? :-)

**Comment by simoneb** [comment]
@piccoloaiutante I'd like to, but I'm visiting EXPO on that day :( I'm planning a new event in Reggio Emilia though!

**Comment by teomurgi** [comment]
@piccoloaiutante  Yeah, I can mentor on that day

**Comment by lambrojos** [comment]
@enaguero ?

**Comment by piccoloaiutante** [comment]
good morning fellows,

which workshops do we want to use during this node school? These are my suggestion :-)
- learnyounode
- streamadventure
- make me hapi
- learn uv

**Comment by piccoloaiutante** [comment]
ping @lambrojos
@nkint
@kamakay
@kamakay workmates
@teomurgi

**Comment by nkint** [comment]
I tried also the webgl ones and I liked them.. not strictly node.js but still very interesting to me.. any one interested?

**Comment by teone** [comment]
I would suggest 
- `tower-of-babel`
- `promise-it-wont-hurt`
  Usefull for all js dev, not only node.

**Comment by piccoloaiutante** [comment]
Ok but we should focus around a group of 4 core workshop so we can be ready.

**Comment by teone** [comment]
- tower fo babel
- learnyounode
- makemehapi
- promise it wont hurt

could work?

**Comment by piccoloaiutante** [comment]
i would change promise it won't hurt with stream adventure and then for me it's ok

**Comment by teone** [comment]
For me is ok

**Comment by piccoloaiutante** [comment]
@lambrojos
@nkint
@kamakay
@kamakay workmates
@teomurgi

is it ok for you? What would you like to teach?

**Comment by teomurgi** [comment]
I'd like to teach learnyounode

**Comment by kamakay** [comment]
Hi,

I Will the only one from my group. I would like to "touch" learnyounode
Il 26/Ott/2015 18:21, "Matteo Murgida" notifications@github.com ha
scritto:

**Comment by piccoloaiutante** [comment]
Hey guys quick feedback over the expectation from participants. This is a quick poll over few of them:

-learyounode 9
-javascript 7
-expressworks 5
-asyncyou 4
-howtonpm 4

then lets switch makemehapi to express works. How about it?

**Comment by teone** [comment]
For me is ok,
the only I would suggest is to change asyncyou to promise-wont-hurt as the goal is the same and promises are now standard.

Anyway I can help where is needed, no preference. 

Only it could be that I'll be 15 min late as I have a scrum review at 6:00pm, but I'll do that directly from mikamai.

See you tomorrow

**Comment by piccoloaiutante** [comment]
so final list for tomorrow evening should be:
- stream adventure
- learnyounode
- expressworks
- promise it wont hurt

**Comment by piccoloaiutante** [comment]
i'll go for mentoring at stream adventure

**Comment by teone** [comment]
As learnyounode is crowded I'll go for promise. 
@lambrojos do you know many peoples are we expecting?

**Comment by kamakay** [comment]
Sorry guys, i ve got a flu :(
Hope you ll have a fun.

Roberto
Il 27/Ott/2015 20:50, "Matteo" notifications@github.com ha scritto:
