### ISSUE TITLE
heads up: node 4 and workshoppers on Windows

### ISSUE THREAD

**Issue by simoneb** [nodeschool/italy#24]
Just a note about a known incompatibility of most workshops with Node 4.x on Windows, still unresolved today.

If you're running Windows you should install Node 0.12.x or the main menu of most workshops won't work, making them basically unusable.

**Comment by marcopiraccini** [comment]
Hi Simone, what is exactly the error? Just to recognize it....

**Comment by simoneb** [comment]
You can't move around the menu with the keyboard (which is the only way to
interact with the menu), making the workshop basically unusable. This for
sure applies to most entry-level workshops, javascripting and learnyounode
for example.

**Comment by kildem** [comment]
In our nodeschool event in Cagliari some people resolve this issue installing ConEmu

**Comment by kildem** [comment]
ConEmu

**Comment by marcopiraccini** [comment]
It can be solved also installing a real OS :D
