### ISSUE TITLE
Linux Day Modena 24th October

### ISSUE THREAD

**Issue by simoneb** [nodeschool/italy#25]
[UPDATE: updated Bologna to be Modena in fact, the event is in Modena, not Bologna]

Hi,

the organizers of the Linux Day event in Modena asked us to hold a NodeSchool session during the event.

http://linuxday.conoscerelinux.it/

It will be this Saturday 24th October at 2PM.

Anyone's in for mentoring?

**Comment by marcopiraccini** [comment]
I'm out of Italy this we, sorry :(

**Comment by gpad** [comment]
I'm sorry but I'll be in Ferrara to talk about Elixir/Erlang :-(

2015-10-19 9:44 GMT+02:00 Simone Busoli notifications@github.com:

**Comment by mcollina** [comment]
I have a wedding :/
Il giorno lun 19 ott 2015 alle 10:08 GPad notifications@github.com ha
scritto:

**Comment by simoneb** [comment]
You're not getting married are you? :D

**Comment by mcollina** [comment]
Nope, a friend is getting married
Il giorno lun 19 ott 2015 alle 10:48 Simone Busoli notifications@github.com
ha scritto:

**Comment by simoneb** [comment]
:)

**Comment by double-m** [comment]
I'll be in!

**Comment by simoneb** [comment]
:+1:

**Comment by diegobent** [comment]
Sorry Simone but I can't!
