### ISSUE TITLE
Bologna - 3th December

### ISSUE THREAD

**Issue by marcopiraccini** [nodeschool/italy#28]
We have the availability of WCAP for Thursday, December 3 (18-21), I will publish an eventbrite event soon
In the meanwhile, any idea on the subject(s)?

**Comment by simoneb** [comment]
I should be able to join as a mentor, and we have JetBrains' coupons! About the subjects, no personal preference :smile:

**Comment by marcopiraccini** [comment]
Well, my proposal is to focus on the "ES6" workshop, since there are quite a few: 
- Count to 6
- Learn Generators
- ESNext Generation
- Tower of Babel

**Comment by simoneb** [comment]
Why not! Sounds good for me

**Comment by marcopiraccini** [comment]
Here the eventbrite event: http://www.eventbrite.com/e/nodeschool-bologna-es6-tickets-19571950230

**Comment by marcopiraccini** [comment]
Ok, event full :). Now mentors needed :D!

**Comment by simoneb** [comment]
I'm in

**Comment by gpad** [comment]
Count on me !!!!
