### ISSUE TITLE
Rome

### ISSUE THREAD

**Issue by Giuliano84** [nodeschool/italy#3]
At Stamplay we do massive use of Javascript and Node all platform-wide. 
Our dev team is in Rome so we're probably in the perfect position to run this one. 
Looking fwd to hear more about it

**Comment by Giuliano84** [comment]
Hey guys, any update?

**Comment by mcollina** [comment]
We are in with a 3-4 hour workshop inside codemotion. Official annoucement coming soon :dancers:. My bad I did not post the update here :(.

**Comment by piccoloaiutante** [comment]
Yeah! Well done ;-) Do you know when it will be? Friday or Saturday?

**Comment by marcopiraccini** [comment]
Great guys! Of course, if needed I'm available as mentor!

**Comment by mcollina** [comment]
Coo, so we should be 8-9 mentors, we can easily handle ~40-50 people. NICE!

**Comment by Giuliano84** [comment]
Allright, @mcollina can you put us in the loop so we can coordinate all the pr stuff ?

**Comment by piccoloaiutante** [comment]
@Giuliano84 good idea

**Comment by mcollina** [comment]
There is no loop ATM, I discussed this very briefly during the call last Friday.

**Comment by Giuliano84** [comment]
np, just let's work together to spread it to the world :)

**Comment by Nss** [comment]
I'm in as mentor as well, let me know

**Comment by Mte90** [comment]
I'm one of the member of RomaJS https://plus.google.com/u/0/communities/114324393897443067092
Tone of our meetings a few months ago was dedicated just to nodeschool.io

**Comment by mcollina** [comment]
Oh, that's a pity! You should have registered in the main nodeschool.io website! I did not know!

(I thought RomaJS was more about doing fronted stuff)

You can still build that Rome Chapter, if you want to!

Will you be at Codemotion?

**Comment by Mte90** [comment]
I will be at codemotion as a speaker (i hope with this https://github.com/Mte90/Talk-FF-OWA).
I'm not only a member and speaker of romajs but now we are doing some meetup focues only on nodejs. Javascript is Javascript :-D Check on the community page.

**Comment by mrgamer** [comment]
I have no idea how many mentors and/or attendees are you preparing the event for, but I'm posting here to give my availability for mentoring and to keep following the initiative.

**Comment by mcollina** [comment]
The nodeschool workshop at Codemotion is confirmed.

Tentative mentor list:
- @piccoloaiutante 
- @Giuliano84 
- @marcopiraccini 
- @Nss 
- @mafintosh 
- @mcollina (yuk, me)
- @Mte90 (if it is ok for you :))
- @rjrodger (you will be there anyway :D)
- @mrgamer 

@Giuliano84 your stamplay colleagues would like to fill in as mentors or as attendees?

We aim at 60 attendees, so we should try to have 11-12 mentors.

**Comment by teomurgi** [comment]
Which is the exact date of the workshop?

**Comment by mcollina** [comment]
The 27th March at 14:00.

**Comment by piccoloaiutante** [comment]
I'll be doing again learnyounode

**Comment by mcollina** [comment]
I can do goingnative again, or learnyounode if it is needed :).

**Comment by LucaLanziani** [comment]
Argh, I have my talk at 14:00.

On 28 February 2015 at 15:18, Matteo Collina notifications@github.com
wrote:

> I can do goingnative again, or learnyounode if it is needed :).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/italy/issues/3#issuecomment-76527774.

## 

_Luca Lanziani_ - Software Engineer  _e-mail_ : luca.lanziani@gmail.com
_site_ : lanziani.com_skype_ : luca.lanziani

**Comment by mcollina** [comment]
Aaarg :(. Worst-case, you join us after your talk :). Best-case, we ask if you could be moved to the morning or Saturday.

**Comment by mafintosh** [comment]
Looking forward to this!

**Comment by marcopiraccini** [comment]
Probably it's better to choose a set of workshops first with different levels of skills, then we will form the tables at the moment (we don't have "registrations"). For this reason, it's better if the mentors could cover much of the workshops as possible of this "set".

My proposal:
- Learnyournode
- Stream-adventure
- Functional Javascript
- Async you
- Going native

I can do all of them (ok, never done going-native, but I will able to complete it before the Codemotion :))

**Comment by mcollina** [comment]
I think we should offer some web-oriented stuff :).

I would drop 'Functional Javascript' and 'Async You', and add back one of ExpressWorks or MakeMeHapi.

**Comment by colthreepv** [comment]
Everyone always asks for web-oriented stuff... I agree on covering that.

Between the proposed workshops I think `Functional javascript` is quite interesting, I hope people embraces it, as it could make them better coders, start thinking as javascript as a language, not just translating code from C/python and name the file `.js`

Regarding `Async you`, maybe it's a little anachronistic.
I know it's _so_ widely used, but callbacks are just callbacks, once you nailed it, there's not much to learn (except indentation :unamused:).  
I would personally vote for a promise approach as bluebird and native promises are reality today, also the concepts are more abstract, so having someone to nail down the mechanisms could be the real plus of a workshop.

NOTE: I can't cover `Going native`, although I'm intrigued following it  :open_mouth: !

**Comment by mcollina** [comment]
I will do going native :).

**Comment by piccoloaiutante** [comment]
@mcollina yes i would go more for web stuff. i could also do ExpressWork

**Comment by Mte90** [comment]
I'm not a pro programmer in NodeJS but i can help, i work mainly with javascript on client side.
I relaunch the discussion in the RomaJS group.

PS: as information there will be a Mozilla italian meetup during the codemotion but I do not know hours.

**Comment by Giuliano84** [comment]
Sorry I've been completely swamped over the last weeks. Probably we are able to join with 2/3 mentors, I'm double checking with the team and we'll let you know by tomorrow. Here is a shortlist of wshop we can help with:
- https://github.com/rvagg/learnyounode
- https://github.com/azat-co/expressworks
- https://github.com/stevekane/promise-it-wont-hurt
- https://github.com/bulkan/async-you
- https://github.com/timoxley/functional-javascript-workshop

**Comment by claudiopetrini** [comment]
Hi, I'm from Giuliano's team I could do `async-you` and `expressworks`

**Comment by criroselli** [comment]
Hi guys, 
I'm from Stamplay (Giuliano's team ), I can  help in `async-you` and `expressworks`.

**Comment by mirkods** [comment]
Hi guys,
I'm from Stamplay and as my colleagues I can contribute in async-you and expressworks

**Comment by mcollina** [comment]
@mrgamer @Mte90 we need your emails to be listed as co-speaker at the event.

**Comment by Mte90** [comment]
mte90net at gmail.com :-)

**Comment by marcopiraccini** [comment]
Great event guys! :)
Approx 60 attendees, all focused for nearly 3 hours in playing with Node!

**Comment by mcollina** [comment]
I think we can safely close this, @marcopiraccini! The event was a blast!
