### ISSUE TITLE
Modena - February 2016

### ISSUE THREAD

**Issue by simoneb** [nodeschool/italy#30]
Hi everyone and happy new year! :tada: 

Let's begin 2016 with an event in Modena in early February.

What about **Saturday 6th February**? Who's in?

Event live! https://nodeschool-modena-feb2016.eventbrite.com

**Comment by marcopiraccini** [comment]
Saturday is good. I will probably be in.

**Comment by simoneb** [comment]
Oh, to not forget that we'll be giving away JetBrains license coupons, this time we'll have 4 licenses for attendees!

**Comment by marcobreveglieri** [comment]
I would gladly participate! :)

**Comment by grimimirg** [comment]
Sounds good for me. It would be my first time! Looking forward to be there!

**Comment by simoneb** [comment]
Event live! https://nodeschool-modena-feb2016.eventbrite.com
