### ISSUE TITLE
Milan 1st of March

### ISSUE THREAD

**Issue by piccoloaiutante** [nodeschool/italy#31]
I'm planning a node school event at link.me venue. Who is up for it?

**Comment by lambrojos** [comment]
Me (of course!) Sorry for the late answer

@nkint?

**Comment by nkint** [comment]
Yes for sure I'm in!
Also, I would like to involve WebGL community to make a session of those workshop:

https://github.com/stackgl/shader-school
https://github.com/stackgl/webgl-workshop

Even if it's not node.js centric I think it could be interesting.. What do you think?

If node.js is the priority I can manage another session for the WebGL thing but it's part of node school anyway.. I think someone got something similar in Bologna during the Robot Festival.. do I remember well?

**Comment by kamakay** [comment]
Hi,

I want attend! Hope to see you soon guys.

Roberto
Il 07/Feb/2016 22:53, "alberto" notifications@github.com ha scritto:

**Comment by piccoloaiutante** [comment]
@kamakay we're going to make tickets available soon so you can get yours for free.

@nkint in the last edition we had a big quota of participants that  were completely new on node.js. I would suggest to have three workshop:
- learnyounode as starting point
- makemehapi for someone who wants to explore web stack

and then an advanced one that could be webgl or either stream-adventure. What do you think guys?

**Comment by lambrojos** [comment]
I think that webgl could draw in people coming from a greater range of contexts (front end, artists..) maybe we could do both webgl and stream-adventure? I think they are both advanced,    but in a very different way..

**Comment by piccoloaiutante** [comment]
yep no problem for it  @lambrojos 

@teomurgi are you joining us?

**Comment by teomurgi** [comment]
@piccoloaiutante: that is the only day of that week in which I'm busy... sorry

**Comment by nkint** [comment]
Good!

**Comment by piccoloaiutante** [comment]
https://www.eventbrite.it/e/biglietti-nodeschool-21623864561

**Comment by piccoloaiutante** [comment]
It seems that we are reaching a good number of participants, roughly 50 people. Given an 50% drop rate there should be 25 people :-)

So quick recap on mentors:

me 
@lambrojos 
@nkint 

is there any other mentor that we could contact?

**Comment by simoneb** [comment]
@piccoloaiutante I'd like to join but during the week I'm afraid I can't make it

**Comment by piccoloaiutante** [comment]
no worries @simoneb  :-)

**Comment by lambrojos** [comment]
Ok we'll get one more mentor from khronos group, for the webgl workshop, unfortunately he has not github account so I can't mention him

We'll also get some free pizza, courtesy of khronos group :)

**Comment by RedsAnDev** [comment]
So, when?

**Comment by piccoloaiutante** [comment]
@RedsAnDev see you on Tuesday?

**Comment by RedsAnDev** [comment]
I'm very busy in this times. So, if you make a "summer node party-cool-name" I could be there.

**Comment by piccoloaiutante** [comment]
The event is almost sold out! See you all tomorrow evening :-)

**Comment by Granze** [comment]
Hi guys,
  it would be nice if we can try not to overlap our events in the future.

Usually, we (Milano JS) meet the first Tuesday of the month. Anyway, we schedule our meetups well in advance and all the info can be found on [our website](http://milanojs.com) and on the [MTS calendar](http://milanotechscene.it/#calendar) as well. The latter was born to avoid these situations.

Nodeschool is a great initiative and I know is time-consuming and, of course, the same is for Milano JS.
It's a pity to force the JS community to choose wich event to attend, isn't it?

:wave:

**Comment by piccoloaiutante** [comment]
@Granze definitely a pity. I'm sorry for this issue. I'll try to avoid this situation in future.
