### ISSUE TITLE
nodeSchool international day - 21/5/2016

### ISSUE THREAD

**Issue by marcopiraccini** [nodeschool/italy#32]
See: http://nodeschool.io/international-day/

We must organize something!

**Comment by mcollina** [comment]
Bologna?

**Comment by marcopiraccini** [comment]
Yes, trying with WCAP, but the problem is that WCAP is closed on Saturday. I'm still awaiting a response from them.

**Comment by marcopiraccini** [comment]
Well, not yet confirmed...but probably we can do the international day in Bologna :)

**Comment by mcollina** [comment]
Ping, any update on this?

**Comment by marcopiraccini** [comment]
Not yet...but I should have some very soon

**Comment by marcopiraccini** [comment]
nodeSchool international day confirmed in Bologna saturday 21/5 :)
More details coming...

**Comment by marcopiraccini** [comment]
Here the evenbrite link! https://www.eventbrite.it/e/biglietti-node-school-international-day-25134019529

**Comment by crishrpz** [comment]
hello everybody , the next in Milan?

**Comment by marcopiraccini** [comment]
Why not? :)
