### ISSUE TITLE
Cagliari (RosaDigitale)

### ISSUE THREAD

**Issue by kildem** [nodeschool/italy#33]
We are planing a nodeshool event in Cagliari on March 10th.
this would be an event mainly focus on female.

Registration page: https://nodeschool-rosa-digitale-ca.eventbrite.it

**Comment by simoneb** [comment]
You may want to look up previous discussion on the topic.

https://github.com/nodeschool/organizers/issues/235

What's the rationale behind restricting the event to women only?

**Comment by kildem** [comment]
@simoneb look at my discussion about this subject here: https://gitter.im/nodeschool/italy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by kildem** [comment]
the aim is bridging the gender gap and Encourage women to know programming

**Comment by kildem** [comment]
The event is LIVE!!!

**Comment by kildem** [comment]
The event was a success :smile:

**Comment by kildem** [comment]
Event photos:
<a href="https://www.facebook.com/511182319088848/photos/ms.c.eJw9kdmNxUAIBDNacR~;5J7YeoN~_PpVJBA2MXDwotU1am~_vNlGWYD~_zIfm2bY9w1wUGdn5LHTeOnjmHxK5Of2E~;qLx4cfN02eKHysJ3h7~;VpXn7T1rGBelmOe~;aJvvxRehg~;68qXr9sm04YTPmnl092f59Mvdk715cvXF~;OolzhfNvZIB3nxDva43eOmX52XwOfV071nmywzux4X7ynP6HXkpk0~;wJeMV~;Xuf~;PKqJs~_xf8~;8bwxY1t9~_LfXyDP~_jd3~;D~;m3zvoX~;3eZvHuvP29RHg7c~;7B~_8goiD.bps.a.525606257646454.1073741832.511182319088848/525606384313108/?type=3&theater" target="_blank">click here</a>
