### ISSUE TITLE
Modena 23 June 2016

### ISSUE THREAD

**Issue by simoneb** [nodeschool/italy#37]
Hey there, we're organizing an event in Modena on Thursday, 23 June, anyone's in?

**Comment by mpolci** [comment]
Hi, I'm interested.

**Comment by simoneb** [comment]
We'll do it here: http://conoscerelinux.org/dove-siamo/

Details will follow

**Comment by bslbar** [comment]
Hi! I'm also interested but I would like to know some information.
What time will it start? How long will it be? :)

**Comment by simoneb** [comment]
Hi @LucaBasilico, it's been postponed to another date, yet to be decided. I'll post more info here.
