### ISSUE TITLE
Stickers!

### ISSUE THREAD

**Issue by mcollina** [nodeschool/italy#6]
So, the first event is approaching and fast #1.

I would like to have stickers for the event: I am attaching a design.

Let me know what you think.

What's the top place to order them? @finnp where di you order the BER ones?
![logo](https://cloud.githubusercontent.com/assets/52195/5797927/fb68fa04-9fc1-11e4-899a-04c92cc14de5.png)

If anybody would like to do any tweaks, please let me know!

**Comment by piccoloaiutante** [comment]
Fine for me  but i'm not a designer  :-P

**Comment by simoneb** [comment]
I'm not a designer either, what you did is well superior to anything I could do myself. As for ordering them, I never did it but I'll try to collect some info.

**Comment by mcollina** [comment]
If you can order them, that would be superb! I'll refund you at the event!

**Comment by marcopiraccini** [comment]
Maybe it's better if we establish a budget and then we split the sum between the mentors.

**Comment by teomurgi** [comment]
sure we can split the sum

**Comment by mcollina** [comment]
Can somebody order them? Then we'll split :D. I am a little full of stuff to do this week, and then I'm at NodeSummit next week, and then we have the workshop :dart:. So maybe they won't ship on time if we do not order them now :).

Thank so much for the good guy that do the job :D.

**Comment by giuscri** [comment]
ok for splitting the sum, but *where* we can order them?

**Comment by mcollina** [comment]
I think a good guide is https://github.com/nodeschool/berlin/issues/3

**Comment by giuscri** [comment]
I'm going to check it later today

**Comment by Giuliano84** [comment]
The german's breakdown is pretty useful. Regarding our edition I would stick to their kind of convention and doing so avoid to fill the logo with colours

**Comment by mcollina** [comment]
@Giuliano84 would you like to make another (maybe better) draft?

**Comment by piccoloaiutante** [comment]
I have already used http://www.pixartprinting.it and http://www.nextdayflyers.com/sticker-printing/ for other events. If you want I can go on with it.

**Comment by giuscri** [comment]
@piccoloaiutante, can you handle it easily? it would be great

**Comment by piccoloaiutante** [comment]
Yes i'm going to order them now, 80 for the first batch and we'll see how good they are.

**Comment by piccoloaiutante** [comment]
@mcollina @Giuliano84 let me know when the logo is ready to sent for print

**Comment by mcollina** [comment]
@piccoloaiutante get the logo printed. We'll go with mine as it is late. Can you get them printed and at your place by Wed/Thu?

**Comment by piccoloaiutante** [comment]
@mcollina  i've just sent the logo and we should get 200 stickers by this thursday

**Comment by mcollina** [comment]
GREAT!!!!

**Comment by piccoloaiutante** [comment]
We have it :+1: 
![img_20150226_094045705](https://cloud.githubusercontent.com/assets/867842/6388947/a43dcb96-bd9f-11e4-927d-fbf0344db71e.jpg)

https://twitter.com/nodeschool_it/status/570873401612623872

**Comment by mcollina** [comment]
Let's close the issue then! :dancers:
