### ISSUE TITLE
404 error for Code of Conduct link on http://nodeschool.io/italy/

### ISSUE THREAD

**Issue by rjack** [nodeschool/italy#7]
Hi,

I just noticed that this link on http://nodeschool.io/italy/ is broken:

![Screenshot](http://i.imgur.com/6Q67UZy.png)

It points to https://github.com/nodeschool/italy/blob/master/codeofconduct.md that returns a 404 error.

Ciao,
Giacomo

**Comment by mcollina** [comment]
Hi Giacomo! Would you mind send a PR for fixing this? 

I propose to follow http://confcodeofconduct.com/ and http://it.confcodeofconduct.com/

**Comment by marcopiraccini** [comment]
Ok for me

**Comment by rjack** [comment]
Done!
