### ISSUE TITLE
Bologna: 22/4

### ISSUE THREAD

**Issue by marcopiraccini** [nodeschool/italy#9]
Informally we have the OK to make the next event again in WCAP (if we all agree that it's a good place). It should be good to decide a date so that we can ask "officially" and book the place. 

Probably it's a good idea to exclude march (some of us will be busy with the Codemotion in Rome), moreover...we are already in march, so it's too late! :))

So probably it's good to chose a date in April, maybe in the second half (after Easter).  
For instance what about the 21 or 22 of April?

UPDATE: Here the updates list of mentors for the 22th:
- @simoneb 
- @marcopiraccini
- @mcollina 
- @gpad (but later)

**Comment by simoneb** [comment]
The dates sound good to me, I'm wondering if we should be aiming at a
different location though, not because WCAP was bad (which indeed it
wasn't!) but rather to make the event not necessarily tied to a specific
location. I'm thinking about spaces provided by companies for instance,
which might be glad to host such an event and would be willing to provide
their spaces for free.

 What do you think?

**Comment by marcopiraccini** [comment]
I can agree that the event should not be tied to a specific location, but it's not simple too find one which fits all the requirements, which are:
- At least 50 person capacity (more is better)
- Free working wifi
- Available after 6 PM (so the people can came after the job)
- Free :)

I know that the guys of coderdojo has the same problem, they often use the "Urbancenter" in Sala Borsa but it is much smaller and (since it's a public place) it's open to everyone and closes at 7 PM. 

However, if you know a company that can host the event, we can ask.

**Comment by simoneb** [comment]
IIRC there were many people from Yoox at the last event, perhaps that may
be an option. I can ask unless someone knows for sure that it isn't a
viable option.

**Comment by mcollina** [comment]
I would prefer a place in the city center. Yoox is really far, but maybe we can poll our attendees!

**Comment by simoneb** [comment]
That's a good point actually. The only thing I would do differently is ask
Yoox first. If they don't give their availability there's no point in even
asking the attendees.

**Comment by marcopiraccini** [comment]
Ok, here my proposal. We can do next event again in WCAP (because we have the informal OK, even if it's better to fix a date quickly). Then, if still the Yoox people comes, we can ask them about the option of organize something in their company (or other places).  

Meanwhile, about the date, it's OK for everyone the 21th or 22th of April?

**Comment by marcopiraccini** [comment]
Ok, no opposition...so I'm going to ask to WCAP if they are free the 21th or 22th of April :).

**Comment by marcopiraccini** [comment]
Ok, the 22th is ok for WCAP.

**Comment by piccoloaiutante** [comment]
i'll try to join you again ;)

**Comment by marcopiraccini** [comment]
Ticket open! https://www.eventbrite.com/e/nodeschool-bologna-aprile-tickets-16217944308

**Comment by simoneb** [comment]
mentors += @simoneb

**Comment by gpad** [comment]
Hi, there is an error on eventbrite, eventbrite is for 21 April but the correct date should be 22 April. I don't know If I can assist as mentor this time, I'll know in some days...

**Comment by simoneb** [comment]
@gpad I think that's the end date for the "sales" of tickets, otherwise looks good to me

**Comment by gpad** [comment]
sorry, my fault :-)

**Comment by marcopiraccini** [comment]
Ok, now we have to decide which workshop we will run.  My opinion is that, we should in general-:
- Run always the "basic" workshop (learnyournode), in case of "new" people. 
- "Present" one (or two) workshop, possibly changing each time

We can decide here a shortlist and then decide the final list with a pool within the inscribed people

My proposal is:
- Bug Clinic 
- Makemehapi (an alternative to express for the API developments)
- Async You

**Comment by mcollina** [comment]
I propose 'how to npm'. I can do that one :). It is the best followup from
learnyounode imho.

I would ditch async you, but that's my gut.
Il giorno lun 30 mar 2015 alle 12:31 Marco notifications@github.com ha
scritto:

**Comment by piccoloaiutante** [comment]
Yes i tend to agree with @mcollina regarding the 'How to Npm'. I'll be also available for that workshop and learnyounode.

**Comment by rjack** [comment]
Already sold-out?

**Comment by piccoloaiutante** [comment]
Yes, i think so. You could register for waiting list. Last time we had several people joining us from waiting list.

**Comment by simoneb** [comment]
@mcollina I'm in for async! (but any other goes)

**Comment by marcopiraccini** [comment]
Ok, if there are no more proposal, this is the short list:
- Learnyournode-
- How to Npm
- Async You
- Bug Clinic
- Makemehapi

**Comment by marcopiraccini** [comment]
In the meanwhile, How many mentors can confirm their presence? We need at least 5-6 mentors.
Copy & append to the list:
- marcopiraccini

**Comment by simoneb** [comment]
I'm in, I'd put the list in the first message of the thread though as @mcollina did for the previous event (it's more accessible than having to scroll down here)

**Comment by marcopiraccini** [comment]
Here the pool results by far:
- Bug Clinic - 4
- Learnyournode - 9
- Makemehapi - 7
- Async you - 2
- How to Npm - 0 (sorry @mcollina  :)).

**Comment by marcopiraccini** [comment]
C'mon guys, we need more mentors! :)

**Comment by LucaLanziani** [comment]
How much do you pay for a mentor? :P

On 16 April 2015 at 16:45, Marco notifications@github.com wrote:

> C'mon guys, we need more mentors! :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/italy/issues/9#issuecomment-93752521.

## 

_Luca Lanziani_ - Software Engineer  _e-mail_ : luca.lanziani@gmail.com
_site_ : lanziani.com_skype_ : luca.lanziani

**Comment by gpad** [comment]
I could arrive at 7 P.M. is it too late?

**Comment by mcollina** [comment]
@Nss I can offer a bed to sleep if you bring a sleeping bag/sheets.

**Comment by mcollina** [comment]
@gpad 7PM is late I think :(

**Comment by marcopiraccini** [comment]
@Nss A couple of (very good) beers :)

**Comment by marcopiraccini** [comment]
@GPad: If you arrive at 7PM it's ok. Of course, we'll start at 6 (6:15 to be realistic :)) but we go on until 9 PM.

**Comment by piccoloaiutante** [comment]
@marcopiraccini i need to check with my wife :-P i'll let you know on monday..

**Comment by gpad** [comment]
@marcopiraccini There is no problem for the end :-)
What exercise do you want I follow?  makemehapi?

**Comment by marcopiraccini** [comment]
The final result is:
- Bug Clinic - 4
- Learnyournode - 13
- Makemehapi - 8
- Async you - 2
- How to Npm - 0 

I'm going to prepare Makemehapi and bug clinic. Also it could be good to say that if someone wants to do one of the workshoppers we did last time (stream-adventure, going native) it's also ok (I know very well stream-adventure and @mcollina can help with going native). 

We are  about 20 for the pizza, but I'm going to book the same day, so maybe this time they don't (hopefully) forget the reservation :)

**Comment by simoneb** [comment]
So I guess we'll do just the first three, in addition to, eventually,
streams and native.

**Comment by piccoloaiutante** [comment]
Unfortunately i cannot make to mentor this time. Hopefully i'l see you in Modena :-)

**Comment by mcollina** [comment]
We need more mentors: @MonsJovis @giuscri @sirmmo can any of you make it?

**Comment by gpad** [comment]
@marcopiraccini Do you count me as mentor also if I arrive around 7.00 P.M.? If yes, What workshop do you want I prepare? I could facilitate learnyounode as the last time, but if possible I would change, and Makemehapi, please let me know ...

**Comment by marcopiraccini** [comment]
@gpad: it's ok if you arrive at 7:00 PM :). Ok for learnyournode and -if you have time- prepare Bug Clinic.

**Comment by gpad** [comment]
@marcopiraccini I'm preparing Makemehapi I don't enough time to prepare also bug clinic I'm sorry.

**Comment by simoneb** [comment]
I'm ok with any of the workshops, we'll find a way to organize the groups.

**Comment by simoneb** [comment]
@marcopiraccini can you sent an email via eventbrite to remind people to unsubscribe if they can't come so to let other people in?

**Comment by marcopiraccini** [comment]
I already sent two mails...I think that is enough :) However about 10 people unsubscribed and where replaced by people in wait-list.

**Comment by simoneb** [comment]
Ouch sorry, my bad, I didn't get a ticket this time, that's why I didn't receive them!

**Comment by marcopiraccini** [comment]
Ok guys...about 45 people! Great Work!
